### ISSUE TITLE
server handle scp 

### ISSUE THREAD

**Issue by ahmadissa** [Scalingo/go-ssh-examples#6]
the server cant handle file transfers though linux command line scp

**Comment by Soulou** [comment]
No it can't, the example server only handle commands, not file transfert. A pull request is welcomed though.

**Comment by ahmadissa** [comment]
i was doing some tests with the help of google :)

check the below, its not complete but its transferring files, i though it might help
`

        package main
        import (
            "fmt"
            "io"
            "io/ioutil"
            "net"
            "os/exec"
            "strings"

            "golang.org/x/crypto/ssh"
        )

        func main() {
            c := &ssh.ServerConfig{
                PasswordCallback: func(c ssh.ConnMetadata, pass []byte) (*ssh.Permissions, error) {
                    if c.User() == "root" && string(pass) == "pass" {
                        return nil, nil
                    }
                    return nil, fmt.Errorf("password rejected for %q", c.User())
                },
            }

            keyBytes, _ := ioutil.ReadFile("key")
            key, _ := ssh.ParsePrivateKey(keyBytes)
            c.AddHostKey(key)

            listener, _ := net.Listen("tcp", "0.0.0.0:2200")
            for {
                tcpConn, _ := listener.Accept()
                _, chans, reqs, _ := ssh.NewServerConn(tcpConn, c)
                go ssh.DiscardRequests(reqs)
                go handleChannels(chans)
            }
        }

        func handleChannels(chans <-chan ssh.NewChannel) {
            for newChannel := range chans {
                go handleChannel(newChannel)
            }
        }

        func handleChannel(newChannel ssh.NewChannel) {
            channel, requests, _ := newChannel.Accept()
            for req := range requests {
                switch req.Type {
                case "shell":
                    go handleShell(channel)
                case "exec":
                    go handleExec(channel, req)
                }
            }
        }

        func handleShell(c ssh.Channel) {}
        func handleExec(c ssh.Channel, r *ssh.Request) {
            cmdString, args, _ := parseCommand(r.Payload)
            fmt.Println(cmdString)

            cmd := exec.Command(cmdString, args...)
            stdout, err := cmd.StdoutPipe()
            if err != nil {
                fmt.Println("SSH: StdoutPipe: %v", err)
                return
            }
            stderr, err := cmd.StderrPipe()
            if err != nil {
                fmt.Println("SSH: StderrPipe: %v", err)
                return
            }
            input, err := cmd.StdinPipe()
            if err != nil {
                fmt.Println("SSH: StdinPipe: %v", err)
                return
            }

            // FIXME: check timeout
            if err = cmd.Start(); err != nil {
                fmt.Println("SSH: Start: %v", err)
                return
            }
            cmd.Start()

            c.SendRequest("exit-status", false, []byte{0, 0, 0, 0})
            r.Reply(true, nil)
            go io.Copy(input, c)
            io.Copy(c, stdout)
            io.Copy(c.Stderr(), stderr)
            if err := cmd.Wait(); err != nil {
                fmt.Println("SSH: Wait:" + err.Error())
                return
            }
            c.SendRequest("exit-status", false, []byte{0, 0, 0, 0})
            return
        }

        func parseCommand(b []byte) (string, []string, error) {

            cmdString := strings.TrimSpace(string(b))
            cmdArray := strings.Split(cmdString, " ")

            cmd := strings.Trim(cmdArray[0], " ")
            cmd = strings.Trim(cmd, "\x00")
            cmd = strings.Trim(cmd, "\r")
            fmt.Println("cmd:" + cmd)
            args := cmdArray[1:]

            return cmd, args, nil
        }


`
